use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;

#[derive(Debug, Deserialize)]
struct Catalog {
    error: Vec<ErrorEntry>,
}

#[derive(Debug, Deserialize)]
struct ErrorEntry {
    code: String,
    phase: String,
    full_code: String,
    message: String,
    severity: String,
    #[serde(default)]
    variant: Option<String>,
    #[serde(default)]
    annotation: Option<String>,
    #[serde(default)]
    help: Option<String>,
    #[serde(default)]
    params: Vec<Param>,
    #[serde(default)]
    messages: Option<Messages>,
}

#[derive(Debug, Deserialize)]
struct Param {
    field: String,
    ty: String,
}

#[derive(Debug, Deserialize)]
struct Messages {
    some: Option<String>,
    none: Option<String>,
}

fn main() {
    println!("cargo:rerun-if-changed=src/errors/catalog.toml");

    let content = fs::read_to_string("src/errors/catalog.toml").expect("failed to read catalog.toml");
    let catalog: Catalog = toml::from_str(&content).expect("failed to parse catalog.toml");

    let out_dir = env::var("OUT_DIR").unwrap();
    let entries = &catalog.error;

    generate_error_codes(&out_dir, entries);
    generate_humane_code(&out_dir, entries);
    generate_explain(&out_dir, entries);
    generate_semantic_kind(&out_dir, entries);

    eprintln!("Generated {} error codes from catalog", entries.len());
}

// ── Constants ──

fn generate_error_codes(out_dir: &str, entries: &[ErrorEntry]) {
    let mut code = String::from("// Generated by build.rs. DO NOT EDIT.\n\n");
    for e in entries {
        let const_name = e.full_code.replace('-', "_");
        code.push_str(&format!("pub const {}: &str = \"{}\";\n", const_name, e.full_code));
    }
    fs::write(Path::new(out_dir).join("error_codes.rs"), code).unwrap();
}

// ── humane_code() ──

fn generate_humane_code(out_dir: &str, entries: &[ErrorEntry]) {
    let mut code = String::from(
        "// Generated by build.rs. DO NOT EDIT.\n\npub fn humane_code(code: &str) -> &'static str {\n    match code {\n",
    );
    for e in entries {
        code.push_str(&format!("        \"{}\" => \"{}\",\n", e.full_code, e.code));
    }
    code.push_str("        _ => \"S0000\",\n    }\n}\n");
    fs::write(Path::new(out_dir).join("humane_code.rs"), code).unwrap();
}

// ── normalize_code() + get_explanation() + run_explain() ──

fn generate_explain(out_dir: &str, entries: &[ErrorEntry]) {
    let mut normalize = String::from(
        "// Generated by build.rs. DO NOT EDIT.\n\npub fn normalize_code(code: &str) -> &str {\n    match code.trim() {\n",
    );
    for e in entries {
        normalize.push_str(&format!("        \"{}\" => \"{}\",\n", e.full_code, e.code));
    }
    normalize.push_str("        _ => code.trim(),\n    }\n}\n");

    let mut expl = String::from("pub fn get_explanation(code: &str) -> Option<&'static str> {\n    match code {\n");
    for e in entries {
        let msg = format!("{}: {}\n\nType: {} {} severity", e.code, e.message, e.severity, e.phase);
        let help = e.help.as_ref().map(|h| format!("\n\nHow to fix: {}", h)).unwrap_or_default();
        let full = format!("{}{}", msg, help);
        expl.push_str(&format!("        \"{}\" => Some(\"{}\"),\n", e.code, esc_str(&full)));
    }
    expl.push_str("        _ => None,\n    }\n}\n");

    let run = r#"
pub fn run_explain(code: &str) -> Result<(), String> {
    let normalized = normalize_code(code);
    match get_explanation(normalized) {
        Some(expl) => { println!("{}", expl); Ok(()) }
        None => Err(format!(
            "unknown diagnostic code `{}`.\n\nTry a code like `S1002`, `S2002`, or `SNASK-SEM-TYPE-MISMATCH`.",
            code
        )),
    }
}
"#;

    fs::write(Path::new(out_dir).join("explain.rs"), format!("{}{}{}", normalize, expl, run)).unwrap();
}

// ── SemanticErrorKind enum + impl ──

fn generate_semantic_kind(out_dir: &str, entries: &[ErrorEntry]) {
    let sem: Vec<&ErrorEntry> = entries.iter().filter(|e| e.phase == "semantic").collect();
    if sem.is_empty() {
        fs::write(Path::new(out_dir).join("semantic_kind.rs"), "// empty\n").unwrap();
        return;
    }

    // ── Pre-process: detect which entries have Option<Type> ──
    let has_opt: Vec<bool> = sem.iter().map(|e| e.params.iter().any(|p| p.ty == "Option<Type>")).collect();

    // ── Enum definition ──
    let mut en = String::from("// Generated by build.rs. DO NOT EDIT.\n\n");
    en.push_str("#[derive(Debug, Clone)]\npub enum SemanticErrorKind {\n");
    for e in &sem {
        let v = variant_name(e);
        match e.params.len() {
            0 => en.push_str(&format!("    {},\n", v)),
            1 => en.push_str(&format!("    {}({}),\n", v, param_type(&e.params[0].ty))),
            _ => {
                en.push_str(&format!("    {} {{\n", v));
                for p in &e.params {
                    en.push_str(&format!("        {}: {},\n", p.field, param_type(&p.ty)));
                }
                en.push_str("    },\n");
            }
        }
    }
    en.push_str("}\n\n");

    // ── impl message() ──
    let mut msg_impl = String::from("impl SemanticErrorKind {\n    pub fn message(&self) -> String {\n        match self {\n");
    for (i, e) in sem.iter().enumerate() {
        let v = variant_name(e);
        if has_opt[i] {
            msg_impl.push_str(&gen_opt_message(e, &v));
        } else {
            msg_impl.push_str(&gen_simple_message(e, &v));
        }
    }
    msg_impl.push_str("        }\n    }\n\n");

    // ── impl code() ──
    msg_impl.push_str("    pub fn code(&self) -> &'static str {\n        match self {\n");
    for e in &sem {
        let v = variant_name(e);
        let pat = wildcard_pattern(&e.params, &v);
        msg_impl.push_str(&format!("            SemanticErrorKind::{} => \"{}\",\n", pat, e.full_code));
    }
    msg_impl.push_str("        }\n    }\n}\n");

    fs::write(Path::new(out_dir).join("semantic_kind.rs"), format!("{}{}", en, msg_impl)).unwrap();
}

fn gen_simple_message(e: &ErrorEntry, variant: &str) -> String {
    let pat = message_pattern(&e.params, variant, &e.message);
    let mut code = format!("            SemanticErrorKind::{} => {{\n", pat);
    let fmt = fmt_template(&e.message, &e.params, true, "");
    let args = fmt_args(&e.message, &e.params, true, "");
    if args.is_empty() {
        code.push_str(&format!("                \"{}\".to_string()\n", esc_str(&e.message)));
    } else {
        code.push_str(&format!("                format!(\"{}\", {})\n", fmt, args.join(", ")));
    }
    code.push_str("            }\n");
    code
}

fn gen_opt_message(e: &ErrorEntry, variant: &str) -> String {
    let opt_field = e.params.iter().find(|p| p.ty == "Option<Type>").unwrap().field.as_str();
    let pat = full_pattern(&e.params, &variant);
    let some_tpl = e.messages.as_ref().and_then(|m| m.some.as_deref()).unwrap_or(&e.message);
    let none_tpl = e.messages.as_ref().and_then(|m| m.none.as_deref()).unwrap_or(&e.message);
    let some_fmt = fmt_template(some_tpl, &e.params, true, opt_field);
    let none_fmt = fmt_template(none_tpl, &e.params, false, opt_field);
    let some_args = fmt_args(some_tpl, &e.params, true, opt_field);
    let none_args = fmt_args(none_tpl, &e.params, false, opt_field);

    // Remove opt placeholder from none template if present
    let none_fmt_clean = none_fmt.replace(&format!("{{{}}}", opt_field), "");

    format!(
        "            SemanticErrorKind::{} => {{\n                match {} {{\n                    Some(__v) => format!(\"{}\", {}),\n                    None => format!(\"{}\", {}),\n                }}\n            }}\n",
        pat, opt_field, some_fmt, some_args.join(", "), none_fmt_clean, none_args.join(", ")
    )
}

// ── Helpers ──

fn variant_name(e: &ErrorEntry) -> String {
    e.variant.clone().unwrap_or_else(|| {
        let stripped = e.full_code
            .strip_prefix("SNASK-PARSE-").or_else(|| e.full_code.strip_prefix("SNASK-SEM-"))
            .or_else(|| e.full_code.strip_prefix("SNASK-BUILD-")).or_else(|| e.full_code.strip_prefix("SNASK-TINY-"))
            .or_else(|| e.full_code.strip_prefix("SNASK-TOOLCHAIN-")).unwrap_or(&e.full_code);
        let mut res = String::new();
        let mut upper = true;
        for ch in stripped.chars() {
            if ch == '_' { upper = true; }
            else if upper { res.push(ch.to_ascii_uppercase()); upper = false; }
            else { res.push(ch.to_ascii_lowercase()); }
        }
        res
    })
}

fn param_type(ty: &str) -> &str {
    match ty { "String" => "String", "Type" => "Type", "usize" => "usize", "Option<Type>" => "Option<Type>", _ => ty }
}

fn message_pattern(params: &[Param], variant: &str, template: &str) -> String {
    match params.len() {
        0 => variant.to_string(),
        1 => format!("{}({})", variant, params[0].field),
        _ => {
            let used: Vec<&str> = params.iter()
                .filter(|p| template.contains(&format!("{{{}}}", p.field)))
                .map(|p| p.field.as_str())
                .collect();
            let total = params.len();
            if used.is_empty() {
                format!("{} {{ .. }}", variant)
            } else if used.len() == total {
                format!("{} {{ {} }}", variant, used.join(", "))
            } else {
                format!("{} {{ {}, .. }}", variant, used.join(", "))
            }
        }
    }
}

fn wildcard_pattern(params: &[Param], variant: &str) -> String {
    match params.len() { 0 => variant.to_string(), 1 => format!("{}(_)", variant), _ => format!("{} {{ .. }}", variant) }
}

fn full_pattern(params: &[Param], variant: &str) -> String {
    match params.len() {
        0 => variant.to_string(),
        1 => format!("{}({})", variant, params[0].field),
        _ => {
            let fields: Vec<&str> = params.iter().map(|p| p.field.as_str()).collect();
            format!("{} {{ {} }}", variant, fields.join(", "))
        }
    }
}

fn fmt_template(tpl: &str, params: &[Param], include_opt: bool, opt_field: &str) -> String {
    const PLACEHOLDER: &str = "\x00FMT\x00";
    let mut s = tpl.to_string();
    // Replace {field} with sentinel
    for p in params {
        if p.ty == "Option<Type>" {
            if p.field == opt_field && include_opt {
                s = s.replace(&format!("{{{}}}", p.field), PLACEHOLDER);
            }
        } else {
            s = s.replace(&format!("{{{}}}", p.field), PLACEHOLDER);
        }
    }
    // Escape remaining braces for format!()
    s = s.replace('{', "{{").replace('}', "}}");
    // Restore sentinel → {}
    s.replace(PLACEHOLDER, "{}")
}

fn fmt_args(tpl: &str, params: &[Param], include_opt: bool, opt_field: &str) -> Vec<String> {
    let mut args = Vec::new();
    for p in params {
        if p.ty == "Option<Type>" {
            if p.field == opt_field && include_opt {
                args.push("display_type(&__v)".to_string());
            }
            continue;
        }
        if !tpl.contains(&format!("{{{}}}", p.field)) {
            continue;
        }
        if p.ty == "Type" {
            args.push(format!("display_type(&{})", p.field));
        } else {
            args.push(p.field.clone());
        }
    }
    args
}

fn esc_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n")
}
